"""Initial migration: create buildings, activities, organizations

Revision ID: 9e880d84ab69
Revises: 073aecdbc627
Create Date: 2025-10-04 01:53:41.119104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e880d84ab69'
down_revision: Union[str, Sequence[str], None] = '073aecdbc627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
